### ISSUE TITLE
Steup fails, Readme is not Up-to-Date

### ISSUE THREAD

**Issue by rheum** [joliebig/Morpheus#4]
I would like to evaluate morpheus, but so far wasn't able to set it up properly. 
This is probably due to an incompatible TypeChef version in the github repo referenced in the readme:
```
git clone https://github.com/aJanker/TypeChef.git
cd TypeChef
./publish.sh
```
fails, because _publish.sh_ is no longer available.
I would greatly appreciate it, if you could update setup instructions in the readme file.

**Comment by joliebig** [comment]
There is a `./publish.sh` available in the TypeChef repository (see [link](https://github.com/aJanker/TypeChef/tree/master)).

![2017-05-11 13_27_46-ajanker_typechef at master](https://cloud.githubusercontent.com/assets/380818/25947003/d88d6f72-364d-11e7-9415-66f38dee4303.png)

**Comment by rheum** [comment]
First of all, thanks for your help. When I checked out the link and image you sent me, I thought something strange must be going on here, because the publish script is definitely not present when cloning the repository as shown below:
`➜  ~ git clone https://github.com/aJanker/TypeChef.git
Klone nach 'TypeChef' ...
remote: Counting objects: 90081, done.
remote: Total 90081 (delta 0), reused 0 (delta 0), pack-reused 90081
Empfange Objekte: 100% (90081/90081), 110.79 MiB | 1.14 MiB/s, Fertig.
Löse Unterschiede auf: 100% (34175/34175), Fertig.
Prüfe Konnektivität ... Fertig.
➜  ~ cd TypeChef 
➜  TypeChef git:(ckmaster) ls          
ConditionalLib  FeatureExprLib  LICENSE              README.md
CParser         Frontend        log4j2.xml           sbt-launch.jar
CRewrite        genpages.sh     Parameter.txt        typechefsampling.sh
CTypeChecker    haskell         ParserFramework      VariationalProgramming.md
deployJar.sh    host            PartialPreprocessor
ErrorLib        JavaParser      project
➜  TypeChef git:(ckmaster) ls -a
.               deployJar.sh    .gitignore  log4j2.xml           sbt-launch.jar
..              ErrorLib        haskell     Parameter.txt        .travis.yml
ConditionalLib  FeatureExprLib  host        ParserFramework      typechefsampling.sh
CParser         Frontend        .idea       PartialPreprocessor  VariationalProgramming.md
CRewrite        genpages.sh     JavaParser  project
CTypeChecker    .git            LICENSE     README.md
➜  TypeChef git:(ckmaster)`

Then I realized that git automatically checked out the ckmaster branch instead of the master branch. The former does not contain a publish.sh. I believe the issue is that github is currently setup to us ckmaster as default branch?

**Comment by joliebig** [comment]
The default branch points to "master" in the projects github configuration. However, there seems to be a change in the git client/server behavior with respect to where HEAD points to; see [link](https://stackoverflow.com/questions/18726037/what-determines-default-branch-after-git-clone). To overcome this issue, I added `git checkout master` to the readme.
